### ISSUE TITLE
can't use the app

### ISSUE THREAD

**Issue by airtonix** [MegaMark16/django-cms-themes#1]
1. to my existing cms project i tried to use this app with.
2. (djangocms-template)user@host:~/Dev/Projects/djangocms-template/$ pip install django-cms-themes
3. put cms_themes in INSTALLED_APPS in settings
4. set PROJECT_DIR in settings
5. (djangocms-template)user@host:~/Dev/Projects/djangocms-template/$ ./project/manage.py syncdb
6. receive error : django.db.utils.DatabaseError: no such table: cms_themes_theme
7. (djangocms-template)user@host:~/Dev/Projects/djangocms-template/$ ./project/manage.py migrate
8. receive error : django.db.utils.DatabaseError: no such table: cms_themes_theme

**Comment by ryanrca** [comment]
I am reproducing this same issue on CentOS 5.5.
Have you found any workarounds?

**Comment by airtonix** [comment]
yes, however I don't remember successfully producing a complete working demonstration.

I did however move past this particular error.

I will post details in the next few days when I have time off from work.

**Comment by airtonix** [comment]
By the way, I'm not sure it will matter what operating system you use.

**Comment by MegaMark16** [comment]
Hey airtonix, thanks for fixing this.  Sorry for the delay, but I'll keep a closer eye on my Github notifications going forward. 

ryanrca, can you confirm that this resolved the issue for you?

**Comment by alexsosic** [comment]
Same problem here...solutions?

**Comment by MegaMark16** [comment]
Oops, logged in as the wrong account.

Hey @alexsosic, I have pushed the changes from @airtonix up to Pypi, so you should be able to pip install this and use it without these errors, but if you do run into any additional errors please let me know.

**Comment by alexsosic** [comment]
Still got the same problem...

Now tried:
pip install --upgrade django-cms-themes
same error...then tried:
pip uninstall django-cms-themes
pip install django-cms-themes
and still have the error when lunching manage.py syncdb

When I comment out cms_themes', in my settings.py
and relaunch syncdb everything works fine.... :(

**Comment by MegaMark16** [comment]
@alexsosic Could you post the stack trace in a gist?

**Comment by alexsosic** [comment]
https://gist.github.com/1566049

**Comment by alexsosic** [comment]
I uninstalled the package via pip uninstall,
then deleted the build/cms_themes directory under my virtualenv
and reinstalled with:
pip install django-cms-themes

The package was cached!

Thanks @MegaMark16 for the support!
